#!/bin/bash
# Awardopedia — Secure credential setup
# Values are never echoed to screen or saved to shell history.

ENV_FILE="$(dirname "$0")/.env"
echo "Writing to: $ENV_FILE"
echo ""

read_secret() {
  local prompt="$1"
  local varname="$2"
  printf "%s: " "$prompt"
  read -rs value
  echo ""
  echo "${varname}=${value}" >> "$ENV_FILE"
}

# Start fresh
cat > "$ENV_FILE" << 'HEADER'
# Awardopedia environment variables
# Generated by setup-env.sh — DO NOT COMMIT THIS FILE
NODE_ENV=production
PORT=3001
HEADER

read_secret "Cloudflare API token"  "CLOUDFLARE_API_TOKEN"
read_secret "DigitalOcean token"    "DO_TOKEN"
read_secret "Stripe secret key"     "STRIPE_SECRET_KEY"
read_secret "Stripe public key"     "STRIPE_PUBLIC_KEY"
read_secret "Anthropic API key"     "ANTHROPIC_API_KEY"
read_secret "SendGrid API key"      "SENDGRID_API_KEY"

# Generate JWT secret automatically
JWT=$(openssl rand -hex 32)
echo "JWT_SECRET=${JWT}" >> "$ENV_FILE"

echo ""
echo "✓ .env written. JWT_SECRET auto-generated."
echo "  Variables set: $(grep -c '=' "$ENV_FILE") total"
echo "  File location: $ENV_FILE"
