"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Sparkles, RefreshCw, Printer } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "";

export default function AwardDetailClient({ awardId, isEnriched }) {
  const router = useRouter();
  const [enriching, setEnriching]   = useState(false);
  const [aiResult,  setAiResult]    = useState(null);
  const [aiLoading, setAiLoading]   = useState(false);
  const [aiError,   setAiError]     = useState(null);

  // Auto-enrich on first load if not yet enriched
  useEffect(() => {
    if (isEnriched) return;
    let cancelled = false;
    setEnriching(true);
    fetch(`${API}/api/awards/${awardId}/enrich`, { method: "POST" })
      .then(r => r.json())
      .then(d => {
        if (!cancelled && d.award) {
          router.refresh(); // re-fetch server component data without full page reload
        }
      })
      .catch(() => {})
      .finally(() => { if (!cancelled) setEnriching(false); });
    return () => { cancelled = true; };
  }, [awardId, isEnriched]);

  async function handleAnalyze() {
    setAiLoading(true);
    setAiError(null);
    try {
      const res = await fetch(`${API}/api/awards/${awardId}/analyze`, { method: "POST", credentials: "include" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to generate brief");
      setAiResult(data.analysis);
    } catch (err) {
      setAiError(err.message);
    } finally {
      setAiLoading(false);
    }
  }

  return (
    <>
      {/* Print button */}
      <div className="no-print" style={{ position: "fixed", bottom: 24, right: 24, zIndex: 100 }}>
        <button
          onClick={() => window.print()}
          style={{ display: "flex", alignItems: "center", gap: 6, background: "var(--color-navy)", color: "#fff", border: "none", borderRadius: 8, padding: "10px 18px", fontSize: "var(--font-size-sm)", fontWeight: 600, cursor: "pointer", boxShadow: "0 2px 12px rgba(0,0,0,0.2)" }}
        >
          <Printer size={15} /> Print Brief
        </button>
      </div>

      {/* Enrichment status */}
      {enriching && (
        <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: "var(--font-size-xs)", color: "var(--color-muted)", marginBottom: "var(--space-4)" }}>
          <RefreshCw size={12} style={{ animation: "spin 1s linear infinite" }} />
          Fetching full contract details from USASpending…
        </div>
      )}

      {/* AI Brief section */}
      <div style={{ borderTop: "1px solid var(--color-border)", paddingTop: "var(--space-4)", marginTop: "var(--space-2)" }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "var(--space-3)" }}>
          <div>
            <div style={{ fontSize: "var(--font-size-sm)", fontWeight: 600, color: "var(--color-navy)" }}>AI Contract Brief</div>
            <div style={{ fontSize: "var(--font-size-xs)", color: "var(--color-muted)" }}>Plain-English summary of what this contract is actually for — 1 credit</div>
          </div>
          {!aiResult && (
            <button
              onClick={handleAnalyze}
              disabled={aiLoading}
              style={{
                display: "flex", alignItems: "center", gap: 6,
                background: "var(--color-amber, #D4940A)", color: "#fff",
                border: "none", borderRadius: 6, padding: "8px 16px",
                fontSize: "var(--font-size-sm)", fontWeight: 600, cursor: aiLoading ? "wait" : "pointer",
                opacity: aiLoading ? 0.7 : 1, flexShrink: 0,
              }}
            >
              <Sparkles size={14} />
              {aiLoading ? "Generating…" : "Generate Brief"}
            </button>
          )}
        </div>

        {aiError && (
          <div style={{ fontSize: "var(--font-size-sm)", color: "#DC2626", background: "#FEF2F2", padding: "10px 14px", borderRadius: 6 }}>
            {aiError}
          </div>
        )}

        {aiResult && (
          <div style={{
            background: "var(--color-bg-subtle, #f7f7f5)", border: "1px solid var(--color-border)",
            borderRadius: 8, padding: "var(--space-4)",
            fontSize: "var(--font-size-sm)", lineHeight: 1.75, whiteSpace: "pre-wrap"
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: "var(--space-3)", fontSize: "var(--font-size-xs)", color: "var(--color-muted)" }}>
              <Sparkles size={12} style={{ color: "var(--color-amber)" }} />
              Generated by Claude — based on NAICS, PSC, agency, and contract data
            </div>
            {aiResult}
          </div>
        )}
      </div>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </>
  );
}
